### ISSUE TITLE
Please, add makefile or eclipse builder.

### ISSUE THREAD

**Issue by egordorichev** [hydren/terrarium#1]
Hello, I want to launch your app. Please, add makefile or eclipse builder.

**Comment by hydren** [comment]
Hello, egordorichev. We are a bit lay on using makefiles, sorry about that. To build the app, we always build through Eclipse. I never tested building it outside Eclipse IDE.

**Comment by hydren** [comment]
If you want to build it, you need the Eclipse IDE for C/C++ Developers. Then you can clone the project through EGit. After this, choose a build configuration corresponding to your environment (Windows or Linux). You need to install Allegro 5 and Box2D development libraries on your OS. On windows, you need them in your MSVC or MinGW.

**Comment by egordorichev** [comment]
Thanks!
